spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: w123s
  redis:
    host: 192.168.178.134

mybatis:
  type-aliases-package: com.wangshuai.bean
  mapper-locations: classpath:mapper/*Mapper.xml
